services:
  api:
    build: 
      context: ../../
      dockerfile: code/deployment/api/Dockerfile
    ports:
      - "8000:8000" 
  app:
    build: ./app
    ports:
      - "8010:8010"
    depends_on:
      - api
